### ISSUE TITLE
Error: spu_create(): Function not implemented

### ISSUE THREAD

**Issue by grifits** [verement/cellminer#25]
Hello
When you run the program:

I get the following error:

(live)ps3min1@redribbon:~/cellminer$ ./cellminer -u gr -p 123 --spe 6 --ppe 2 http://eu1.bitminter.com:3333
[2018-02-19 22:18:11] Cell Miner starting
[2018-02-19 22:18:11] Creating 6 SPU miner(s)
spu_create(): Function not implemented
spu_create(): Function not implemented
/home/ps3min1/cellminer/cellminer.rb:136:in `new': failed to create SPE context (RuntimeError)
	from /home/ps3min1/cellminer/cellminer.rb:136:in `block in main'

sometimes, rarely, this:

(live)ps3min1@redribbon:~/cellminer$ ./cellminer -u gr -p 123 --spe 6 --ppe 2 http://eu1.bitminter.com:3333
[2018-02-19 22:11:56] Cell Miner starting
[2018-02-19 22:11:56] Creating 6 SPU miner(s)
[2018-02-19 22:11:56] Creating 2 PPU miner(s)
spu_create(): Function not implemented
spu_create(): Function not implemented
spu_create(): Function not implemented
spu_create(): Function not implemented
spu_create(): Function not implemented
spu_create(): Function not implemented
/home/ps3min1/cellminer/cellminer.rb:136:in `new': failed to create SPE context (RuntimeError)
	from /home/ps3min1/cellminer/cellminer.rb:136:in `block in main'

Help please, with what it is connected and where to look for the cause of this error.

**Comment by grifits** [comment]
decided
/spu was not mounted
