### ISSUE TITLE
spu_create(): Function not implemented

### ISSUE THREAD

**Issue by tdaugaard** [verement/cellminer#5]
I've installed ruby 1.9 from wheezy (rev. 180 as suggested in another issue) and compiled on my PS3. There were no compile errors or warnings. Here is the result:

```
root@debian:/usr/src/cellminer# ./cellminer -d
Warning: using default server localhost
[2011-06-25 09:22:02] Cell Miner starting
[2011-06-25 09:22:02] Creating 6 SPU miner(s)
spu_create(): Function not implemented
spu_create(): Function not implemented
spu_create(): Function not implemented
spu_create(): Function not implemented
spu_create(): Function not implemented
spu_create(): Function not implemented
/usr/src/cellminer/cellminer.rb:136:in `new': failed to create SPE context (RuntimeError)
        from /usr/src/cellminer/cellminer.rb:136:in `block in main'
```

**Comment by tdaugaard** [comment]
Disregard that, it seems that /spu was not mounted; something that would probably be good to mention as a 'requirement' in the README ;)
